---
- name: update hosts file
  hosts: all
  tasks:
  - name: mod hosts file
    blockinfile: 
      path: /etc/hosts
      block: | 
        {%for host in groups.all%}
        {{hostvars[host].ansible_default_ipv4.address}} {{hostvars[host]ansible_fqdn}} {{hostvars[host].inventory_hostname}}
        {%endfor%}
        
